export const getColumns = () => [
  { columnId: "memberName" },
  { columnId: "relation" },
  { columnId: "employeeName" },
  { columnId: "birthDate" },
  { columnId: "gender" },
  { columnId: "maritalStatus" },
  { columnId: "bank", width: 200, resizable: true },
  { columnId: "bankBranch" },
  { columnId: "bankAccountNumber" },
  { columnId: "email" },
  { columnId: "phoneNumber" },
  { columnId: "nik" },
  { columnId: "fullAddress" },
  { columnId: "employeeId" },
  { columnId: "department" },
  { columnId: "jobLevel" },
  { columnId: "jobTitle" },
  { columnId: "notes" },
  { columnId: "insuranceProvider" },
  { columnId: "plan1" },
  { columnId: "plan2" },
  { columnId: "plan3" },
];
